name: Build Professional GUI Installer

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release with GUI installer'
        required: false
        default: false
        type: boolean

jobs:
  build-gui-installer:
    runs-on: windows-latest
    name: Build Professional GUI Installer
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test application
      run: |
        python -c "from restaurant_billing.db import init_db; init_db(); print('Database test passed')"
        python -c "from restaurant_billing.app import bootstrap; print('Application import test passed')"
        
    - name: Install NSIS
      run: |
        echo "Installing NSIS..."
        choco install nsis -y
        
    - name: Create installer assets
      run: |
        echo "Creating installer assets..."
        
        # Create assets directory
        if (-not (Test-Path "restaurant_billing\assets")) { New-Item -ItemType Directory -Path "restaurant_billing\assets" -Force }
        
        # Create placeholder icon (you can replace with real icon)
        New-Item -ItemType File -Path "restaurant_billing\assets\icon.ico" -Force
        
        # Create placeholder images
        New-Item -ItemType File -Path "restaurant_billing\assets\header.bmp" -Force
        New-Item -ItemType File -Path "restaurant_billing\assets\welcome.bmp" -Force
        
        # Create LICENSE.txt if not exists
        if (-not (Test-Path "LICENSE.txt")) {
            @"
MIT License

Copyright (c) 2024 HUNGER Restaurant Billing System

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"@ | Out-File -FilePath "LICENSE.txt" -Encoding UTF8
        }
        
    - name: Build GUI Installer
      run: |
        echo "Building professional GUI installer..."
        
        # Set NSIS path
        $nsisPath = "C:\ProgramData\chocolatey\lib\nsis\tools\makensis.exe"
        
        # Build the installer
        & $nsisPath installer.nsi
        
        if ($LASTEXITCODE -eq 0) {
            echo "GUI installer built successfully!"
            ls -la "HUNGER-Restaurant-Billing-Installer.exe"
        } else {
            echo "GUI installer build failed!"
            exit 1
        }
        
    - name: Upload GUI Installer
      uses: actions/upload-artifact@v4
      with:
        name: hunger-restaurant-billing-gui-installer
        path: HUNGER-Restaurant-Billing-Installer.exe
        
    - name: Create Release
      if: github.event_name == 'workflow_dispatch' && inputs.create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }} - Professional GUI Installer
        body: |
          ## HUNGER Restaurant Billing System v${{ github.run_number }}
          
          ### Professional GUI Installer
          - **File**: HUNGER-Restaurant-Billing-Installer.exe
          - **Type**: Professional Windows GUI Installer
          - **Size**: Self-contained executable
          
          ### Features
          - 🖥️ **Professional GUI**: Modern Windows installer interface
          - 🔧 **Automatic Setup**: Installs Python dependencies automatically
          - 🗄️ **Database Init**: Initializes SQLite database
          - 🖱️ **Desktop Integration**: Creates shortcuts and start menu entries
          - 🗑️ **Uninstaller**: Complete removal with registry cleanup
          - 📋 **Registry Entries**: Proper Windows integration
          
          ### Installation
          1. **Download**: HUNGER-Restaurant-Billing-Installer.exe
          2. **Run**: Double-click the installer
          3. **Follow**: The installation wizard
          4. **Launch**: From desktop shortcut or start menu
          
          ### System Requirements
          - Windows 7 or later
          - Python 3.11+ (installer will check and guide you)
          - 4GB RAM minimum
          - 500MB free disk space
          
          ### Default Login
          - Username: `owner`
          - Password: `1234`
          
          ### Support
          - GitHub: https://github.com/shihan84/hunger-rest
          - Issues: https://github.com/shihan84/hunger-rest/issues
        files: HUNGER-Restaurant-Billing-Installer.exe
        draft: false
        prerelease: false
